---
- name: "Manage NFS exports"
  tags:
    - nfs
    - nfs.export
  ansible.builtin.import_tasks: export.yaml

- name: "Manage SELinux for NFS server"
  tags:
    - nfs
    - nfs.selinux
  ansible.builtin.import_tasks: selinux.yaml
